name: Keep Render Service Awake

on:
  schedule:
    # Runs every 5 minutes to account for GitHub Actions scheduling delays (which can be up to 15+ minutes)
    - cron: '*/5 * * * *'
  workflow_dispatch: # Allows manual triggering from the GitHub Actions tab

jobs:
  ping-website:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render URL
        run: curl -s https://tourney-pro-cnt8.onrender.com > /dev/null